[package]
name = "we-kzg"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = "0.4.0"
ark-ec = "0.4.2"
ark-ff = "0.4.2"
ark-serialize = "0.4.2"
ark-std = "0.4.0"
blake3 = "1.5.4"
rand = "0.8.5"
thiserror = "1.0.63"
